server:
  port: 9000

spring:
  application:
    name: springboot

#暴露actuator端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
